### ISSUE TITLE
"Feature Request" Getting Minecraft Changelogs of every version

### ISSUE THREAD

**Issue by M1XT3NZ** [AlphaBs/CmlLib.Core#1]
In my opinion, it would be nice to get the changelogs of every Minecraft version.

**Comment by AlphaBs** [comment]
Okay. Do you know where to get changelog?

**Comment by M1XT3NZ** [comment]
To be honest with you no I don't...
I would've probably made a pull request by now... 

I mean the wiki has changelogs but I actually don't think they are complete(I could be wrong though)

And the official Minecraft site only has the changelogs since 1.13 or so.

**Comment by AlphaBs** [comment]
I add that function in CmlLib.Core 2.0.0.

https://github.com/AlphaBs/CmlLib.Core/wiki/Get-Minecraft-Changelogs

this version contains only 6 changelogs, but I will add more versions in the future.

**Comment by M1XT3NZ** [comment]
Found some more changelogs. 
https://mcupdate.tumblr.com/post/38375290540/minecraft-146
Those are basically all changelogs of the game.

It's pretty tedious to find them all but hey :D
