### ISSUE TITLE
Custom instances directory with shared libraries

### ISSUE THREAD

**Issue by LosTigeros** [AlphaBs/CmlLib.Core#11]
Hey is it possible for you to make it possible to be able to use this structure:
.
 * assets (normal assets directory)
 * instances
   * ModPacks
      * MyOwnPack (custom path where client data is saved - "./instances/ModPacks/MyOwnPack")
          * config
          * logs
          * mods
          * natives (temp dir)
          * client.jar
          * options.txt
          * servers.dat
          * MyOwnPack.json
   * OptiFine
   * Vanilla
      * 1.12.2 (custom path where client data is saved - "./instances/OptiFine/Vanilla/1.12.2")
         * logs
         * resourcepacks
         * saves
         * natives (temp dir)
         * 1.12.2.json
         * client.jar
 * libraries (normal libraries directory)

I know I can set a path for the client data (for example to the 1.12.2 Vanilla dir) but can you add possibility to set custom libraries location like we can do for assets?

**Comment by AlphaBs** [comment]
you can do this by below code:

```
var defaultPath = new MinecraftPath();
var myPath = new MinecraftPath(@"./instances/ModPacks/MyOwnPack");
myPath.SetAssetsPath(defaultPath.Assets);
myPath.Library = defaultPath.Library;
myPath.Runtime = defaultPath.Runtime;

var launcher = new CMLauncher(myPath);
// launch codes
```
but you can't change path of natives, client.jar and client.json file. these files will be in `myPath.Versions`

so, i will make it more flexible by adding virtual methods latter.

Thank you !

**Comment by LosTigeros** [comment]
Can you add another function like https://github.com/AlphaBs/CmlLib.Core/blob/9d29d0aa422452acff08e5bd32b80d0b1b16f688/CmlLib/Core/MinecraftPath.cs#L49
but with `basePathForLibraries` argument too?

**Comment by AlphaBs** [comment]
okay i will add it but i dont think basePathForLibraries because you can do that like this

```
new MinecraftPath("basepath","assets")
{
    Library = "library path"
};
```

**Comment by LosTigeros** [comment]
Yeah but it will still create `libraries, resources, runtime, versions` directories in the basepath dir.
