### ISSUE TITLE
Using Fabric

### ISSUE THREAD

**Issue by Bevan0** [AlphaBs/CmlLib.Core#13]
I've created a directory for my game path and I've installed the latest version of Fabric into that directory (using the installer). However, when I type in the Fabric version ("fabric-loader-0.10.8-1.16.4") it doesn't launch and says it doesn't exist. This is the file structure in the game path:

- versions
  - fabric-loader-0.10.8-1.16.4
    - (all the fabric files in here)

- mods
  - (all my mods here)

I am a little confused here, so help would be appreciated.

**Comment by Bevan0** [comment]
Found the issue; tip for everyone is to NOT use %appdata% or any other shortcuts

**Comment by BSDevs-web** [comment]
I want to launch FabticMC too. I have problem with launch too. You found issue for it how to launch and download all around fabricmc. Please Add me on discord: BSDevs#9527.
