### ISSUE TITLE
Nuget package different from here

### ISSUE THREAD

**Issue by FabioZumbi12** [AlphaBs/CmlLib.Core#5]
Hi,

I am updating from CML to this, and already installed the version 2.0.2, but theres some different results.

- As example, `new Minecraft(path)` dont return a path string but returns itself, not what your examples says;
- Theres no `CMLaunch()`, only `MLaunch()`;

And some other things...

Heres the installed version:
![image](https://user-images.githubusercontent.com/5833818/86201987-6c223d00-bb37-11ea-92e5-71eaeddc43b7.png)

Can you check whats wrong?
Thanks!!

**Comment by M1XT3NZ** [comment]
`var path = Minecraft.GetOSDefaultPath(); // mc directory`
This is the way you get the standard Minecraft Path...
`var path = new Minecraft("your minecraft directory);`
This to set it yourself ;)


For example,
you can easily just interchange CMLaunch or MLaunch.

`var launch = new MLaunch(option);`
so yeah documentation might not always be up to date but tbh you shouldn't always follow documentation anyway ;)

**Comment by FabioZumbi12** [comment]
Thanks for fast response, bus as example, i am following the wiki to setup my launcher with this new repository and this:

![image](https://user-images.githubusercontent.com/5833818/86203985-c1ad1880-bb3c-11ea-8f77-e1a47d68a94c.png)

I have no options like on wiki: `var process = launcher.CreateProcess("1.15.2", launchOption);`

This is why i think the sources on nugget are different, and a lot of other different things.

**Comment by M1XT3NZ** [comment]
```
            var launch = new MLaunch(option);
            var process = launch.GetProcess();

            var th = new Thread(() => { StartProcess(process) ;});
```

would be the right.
i guess its actually really confusing..

oh and sry 
```
        private void StartProcess(Process process)
        {
            File.WriteAllText("launcher.txt", process.StartInfo.Arguments);
            
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.RedirectStandardError = true;
            process.StartInfo.RedirectStandardOutput = true;
            process.EnableRaisingEvents = true;
            process.ErrorDataReceived += Process_ErrorDataReceived;
            process.OutputDataReceived += Process_OutputDataReceived;
            process.Exited += Process_Exited;

            process.Start();
            process.BeginErrorReadLine();
            process.BeginOutputReadLine();
        }
```
stole this out of the example program which would also be in the github repository..

**Comment by FabioZumbi12** [comment]
I got that i need to use `new CmlLib.CMLauncher(path);` and not MLaucnher from inside Core!!

Got working vanilla, now i just need to adapt for my Pixelmon version ^^
Any examples?

**Comment by M1XT3NZ** [comment]
Not really,
since im not 100% sure what you want.

![Screenshot_24](https://user-images.githubusercontent.com/29348454/86205463-3ba7c680-bb6a-11ea-92b0-830fa3eff877.png)

you probably want this?
Those are my current installed minecraft versions,
I cant really give you an example because i gave you the full code already i guess?

You can easily start it that way.

**Comment by FabioZumbi12** [comment]
Ill try to use my old resource version as base to make work with my forge pack.

Thank you for help 👍

**Comment by AlphaBs** [comment]
sorry, i will update it asap

**Comment by AlphaBs** [comment]
I found that example codes in readme has some grammatical error, and some codes may confuse user :

```
 //var path = "your minecraft directory";
 var path = Minecraft.GetOSDefaultPath(); // get default minecraft path
```

so I updated readme. thanks for issue.
